# opt-in to Travis's newer/faster container-based infrastructure
sudo: false

# this builds the spec using jekyll
# based on http://www.paperplanes.de/2013/8/13/deploying-your-jekyll-blog-to-s3-with-travis-ci.html
language: ruby
rvm:
  - 2.2
script: bundle exec jekyll build -s spec/ -d build/spec
install: bundle install

# TRAVIS_CI_SECRET=$(cat /dev/urandom | head -c 10000 | openssl sha1)
# travis encrypt "PRIV_KEY_SECRET=$TRAVIS_CI_SECRET"
env:
  - secure: "P8EqpZoin/YTnwel9TTxSSAHtXfZ4M262BKXlYUZmjoQsjyvXDAeZ7yAqgAvX5BeRFrGkBToPiE+V60stdWkPKs3+9COw2BDUB1CULBHhRY9Lxordmz0xVhgEfsoH4f6r6wOlIQ9kuaWhmP+JdB/mzOHZhLch9ziPi8O46Z8t4k="

# ^^^ set PRIV_KEY_SECRET to password used to encrypt spec/id_dsa_travis.enc

# the key is restricted using forced commands so that it can only upload to the directory we need here
# every forced command needs a new key -- generate a pair thusly:
# ssh-keygen -b 4096 -f ~/.ssh/id_dsa_spec213_b4096
# openssl aes-256-cbc -pass "pass:$TRAVIS_CI_SECRET" -in ~/.ssh/id_dsa_spec213_b4096 -out ./spec/id_dsa_travis.enc -a
after_success:
  - ./scripts/travis-publish-spec.sh

# using S3 would be simpler, but we want to upload to scala-lang.org
# after_success: bundle exec s3_website push --headless
